# Generated by Django 5.1 on 2024-09-12 08:43

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=catalog.models.CompressedImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.product",
            ),
        ),
    ]
