# Generated by Django 5.1 on 2024-09-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_description_alter_productimage_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.IntegerField()),
                ("first_name", models.TextField(null=True)),
                ("last_name", models.TextField(null=True)),
                ("username", models.TextField(null=True)),
                ("language_code", models.TextField(null=True)),
                (
                    "favorites",
                    models.ManyToManyField(related_name="users", to="catalog.product"),
                ),
            ],
        ),
    ]
