version: "3"
services:
  prod:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: tooflya-app
    volumes:
      - staticfiles:/app/static
      - data:/app/data
    env_file:
      - .env
    ports:
      - ${APP_PORT}:8000
    restart: always

volumes:
  staticfiles:  
    driver: local
  data:
    driver: local